# Generated by Django 4.1.3 on 2023-04-04 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_task_salary_message_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_pdf',
            field=models.FileField(default=None, upload_to='task/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 14, 41, 31, 188721)),
        ),
    ]
